steps:
- name: 'gcr.io/shard-232101/init-thrashplay-build'
  id: Initialize credentials and settings

- name: 'gcr.io/cloud-builders/mvn'
  id: Compile and release project
  args: ['-X', '--batch-mode', 'release:prepare', 'release:perform']

- name: 'gcr.io/cloud-builders/git'
  id: Compile and release project
  args: ['push', '--tags']
