steps:
- name: 'perl:5'
  id: Configure Maven settings
  entrypoint: bash
  args:
  - '-c'
  - |
    echo "MAVEN CONFIG: $$MAVEN_CONFIG"
    PATTERN="$$NEXUS_PASSWORD" perl -p -e 's/NEXUS_PASSWORD/$$ENV{PATTERN}/g' build/settings.xml.tpl > build/settings.xml
  secretEnv:
  - 'NEXUS_PASSWORD'

- name: 'gcr.io/cloud-builders/mvn'
  id: Compile and package project
  args: ['--settings', 'build/settings.xml', '--batch-mode', 'release:prepare', 'release:perform']

secrets:
- kmsKeyName: projects/shard-232101/locations/global/keyRings/dev/cryptoKeys/google-cloud-builds-key
  secretEnv:
    NEXUS_PASSWORD: 'CiQAseTHTAs7FGbHQUxTJlgJxbQbOhhvzw5+ujbOELVZP3+XX4ISOQDz/FGDbBTKSxt0MfKKkZGb+8XZTepH+iD6DmuDhrHHVzyB0wyUIJRxgKytvxw9a/5X/6o9vZ0l2Q=='