steps:
- name: 'gcr.io/shard-232101/init-thrashplay-build'
  id: Initialize credentials and settings

- name: 'gcr.io/cloud-builders/mvn'
  id: Compile and release project
  args: ['--batch-mode', 'release:prepare', 'release:perform']
