steps:
- name: 'gcr.io/shard-232101/init-thrashplay-build-environment-builder'
  id: Initialize credentials and settings

- name: 'gcr.io/cloud-builders/mvn'
  id: Compile and release project
  args: ['-X', '--batch-mode', 'release:prepare', 'release:perform']
