steps:
- name: 'gcr.io/shard-232101/build-helpers'
  id: Initialize credentials and settings
  args: ['init']
  env:
  - 'DEPLOY_KEY=/thrashplay-dev/secrets/deploy_keys/thrashplay-parent.id_rsa.enc'

- name: 'gcr.io/shard-232101/maven'
  id: Deploy new versions of POMs
  args: ['deploy']

- name: 'gcr.io/shard-232101/build-helpers'
  id: Tag new build
  args: ['tag']

- name: 'gcr.io/shard-232101/build-helpers'
  id: Save local repository
  args: ['save-repository']
