steps:
- name: 'gcr.io/shard-232101/maven-cloud-builder'
  id: Compile and package project
  args: ['--batch-mode', 'release:prepare', 'release:perform']
  secretEnv:
  - 'NEXUS_PASSWORD'

secrets:
- kmsKeyName: projects/shard-232101/locations/global/keyRings/dev/cryptoKeys/google-cloud-builds-key
  secretEnv:
    NEXUS_PASSWORD: 'CiQAseTHTAs7FGbHQUxTJlgJxbQbOhhvzw5+ujbOELVZP3+XX4ISOQDz/FGDbBTKSxt0MfKKkZGb+8XZTepH+iD6DmuDhrHHVzyB0wyUIJRxgKytvxw9a/5X/6o9vZ0l2Q=='