steps:
- name: 'gcr.io/shard-232101/init-thrashplay-build:0.11'
  id: Initialize credentials and settings
  volumes:
  - name: 'root'
    path: '/root'

- name: 'gcr.io/cloud-builders/mvn'
  id: Compile and deploy project
  args: ['deploy']
  volumes:
  - name: 'root'
    path: '/root'

- name: 'gcr.io/shard-232101/save-local-repository:0.11'
  id: Cache local repository to cloud storage
  volumes:
  - name: 'root'
    path: '/root'

