steps:
- name: 'gcr.io/shard-232101/init-thrashplay-build:0.24'
  id: Initialize credentials and settings
  env:
  - 'DEPLOY_KEY=/thrashplay-dev/secrets/deploy_keys/thrashplay-parent.id_rsa.enc'
  volumes:
  - name: 'root'
    path: '/root'

- name: 'gcr.io/cloud-builders/mvn'
  id: Compile and deploy project
  args: ['deploy']
  volumes:
  - name: 'root'
    path: '/root'

- name: 'gcr.io/shard-232101/save-local-repository:0.24'
  id: Cache local repository to cloud storage
  volumes:
  - name: 'root'
    path: '/root'

